modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/Slexom/animal-feeding-trough/issues"
license = "MIT"

[[mods]]
modId = "animal_feeding_trough"
version = "${version}"
displayName = "Animal Feeding Trough"
authors = "Slexom"
description = '''
-
'''
logoFile = "icon.png"

[[dependencies.animal_feeding_trough]]
modId = "forge"
mandatory = true
versionRange = "[${forgeVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.animal_feeding_trough]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.animal_feeding_trough]]
modId = "architectury"
mandatory = true
versionRange = "[${architecturyVersion},)"
ordering = "AFTER"
side = "BOTH"